CREATE TABLE trade_analysis
(
ACTIVITY_DATE       DATE NOT NULL,
CUSTOMER_ID           INTEGER NOT NULL,
STOCK_ID             SMALLINT NOT NULL,
TRANSACTION_AMOUNT        REAL NOT NULL,
NUMBER_OF_TRANSACTIONS    INTEGER NOT NULL,
GAIN_AMOUNT          REAL NOT NULL,
ACTIVITY_YEAR_MONTH INTEGER NOT NULL,
TRADE_TYPE_ID        SMALLINT DEFAULT 0 NOT NULL
);
